[package]
name = "gish"
version = "0.1.0"
authors = ["physics3D <kroener.tobias@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.8.1" # These versions have to match the dependencies of vte-rs
glib = "0.9.3" # These versions have to match the dependencies of vte-rs
gtk = "0.8.1" # These versions have to match the dependencies of vte-rs
hotwatch = "0.4.5"
vte-rs = "0.4.0"
